version: '3'
services:
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'

  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SUPER_ADMIN_EMAIL=peregruochka@gmail.com
      - SUPER_ADMIN_PASSWORD=Password1234
      - SUPER_ADMIN_USERNAME=super_admin
      - JWT_SECRET_KEY=40203abe6e81ed98cbc97cdd6ec4f144
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres

